[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
authors = ["kohdice <k@kohdice.com>"]
edition = "2024"
rust-version = "1.95"
license = "MIT"
repository = "https://github.com/kohdice/mp-rs"

[workspace.dependencies]
mp-core = { path = "crates/mp-core" }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
