[package]
name = "mp-preview"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
mp-ast.workspace = true
mp-parser.workspace = true
mp-renderer.workspace = true

[lints]
workspace = true
