[package]
name = "mp-preview"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
comrak.workspace = true
entities.workspace = true
syntect.workspace = true
thiserror.workspace = true
two-face.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true

[lints]
workspace = true
