[package]
name = "mp"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
mp-preview.workspace = true
terminal_size.workspace = true

[lints]
workspace = true
